(in-package :quickdraw)

(defstruct color
  (r   0d0 :type double-float)
  (g 0d0 :type double-float)
  (b  0d0 :type double-float)
  (a 1d0 :type double-float))

(defun rgba (r g b a)
  (let ((scale (if (every #'integerp (list r g b))
                   (/ 1 255d0)
                   1d0)))
    (make-color
     :r   (* (coerce r 'double-float) scale)
     :g (* (coerce g 'double-float) scale)
     :b  (* (coerce b 'double-float) scale)
     :a (coerce a 'double-float))))

(defun rgb (r g b)
  (rgba r g b 1d0))

(defun rgb-1 (r g b &optional (a 1d0))
  (make-color :r (coerce r 'double-float)
              :g (coerce g 'double-float)
              :b (coerce b 'double-float)
              :a (coerce a 'double-float)))

(defun hsl->rgb (h s l)
  (let* ((h (mod h 360))
         (c (* (- 1 (abs (- (* 2 l) 1))) s))
         (x (* c (- 1 (abs (- (mod (/ h 60) 2) 1)))))
         (m (- l (/ c 2))))
    (multiple-value-bind (r g b)
        (cond ((< h 60)  (values c x 0))
              ((< h 120) (values x c 0))
              ((< h 180) (values 0 c x))
              ((< h 240) (values 0 x c))
              ((< h 300) (values x 0 c))
              (t         (values c 0 x)))
      (values (+ r m) (+ g m) (+ b m)))))

(defun hsl (h s l &optional (a 1d0))
  "H in degrees, S/L in [0,1] or [0,100] if >1."
  (multiple-value-bind (r g b)
      (hsl->rgb h
                (if (> s 1) (/ s 100d0) s)
                (if (> l 1) (/ l 100d0) l))
    (make-color :r r :g g :b b
                :a (coerce a 'double-float))))

(defun hsla (h s l a)
  (hsl h s l a))

(defun color-css (c)
  (let ((r (round (* 255 (color-r c))))
        (g (round (* 255 (color-g c))))
        (b (round (* 255 (color-b c))))
        (a (color-a c)))
    (if (< a 1d0)
        (format nil "rgba(~d, ~d, ~d, ~,4f)" r g b a)
        (format nil "rgb(~d, ~d, ~d)" r g b))))

(defun color->hex (c &key (with-a nil))
  "Return #RRGGBB, or #RRGGBBAA when WITH-A or a < 1."
  (let* ((r (round (* 255 (color-r c))))
         (g (round (* 255 (color-g c))))
         (b (round (* 255 (color-b c))))
         (a (round (* 255 (color-a c)))))
    (if (or with-a (< (color-a c) 1d0))
        (format nil "#~2,'0x~2,'0x~2,'0x~2,'0x" r g b a)
        (format nil "#~2,'0x~2,'0x~2,'0x" r g b))))

(defun hex->color (string)
  (let* ((s (string-trim "#" string))
         (len (length s)))
    (unless (member len '(3 4 6 8))
      (error "Invalid hex color ~s" string))
    (flet ((hex-digit (i) (/ (parse-integer (subseq s i (1+ i)) :radix 16) 15d0))
           (hex-pair  (i) (/ (parse-integer (subseq s i (+ i 2)) :radix 16) 255d0)))
      (if (< len 5)
          (make-color
           :r   (hex-digit 0)
           :g (hex-digit 1)
           :b  (hex-digit 2)
           :a (if (= len 4) (hex-digit 3) 1d0))
          (make-color
           :r   (hex-pair 0)
           :g (hex-pair 2)
           :b  (hex-pair 4)
           :a (if (= len 8) (hex-pair 6) 1d0))))))

(defun rgb->hsl (c)
  (let* ((r (color-r c))
         (g (color-g c))
         (b (color-b c))
         (max (max r g b))
         (min (min r g b))
         (l (/ (+ max min) 2))
         (d (- max min)))
    (if (zerop d)
        (values 0d0 0d0 l)
        (let* ((s (if (> l 0.5d0)
                      (/ d (- 2 max min))
                      (/ d (+ max min))))
               (h (cond ((= max r) (mod (/ (- g b) d) 6))
                        ((= max g) (+ 2 (/ (- b r) d)))
                        (t         (+ 4 (/ (- r g) d))))))
          (values (* 60d0 h) s l)))))

