(in-package :quickdraw)

(deftype unit-double ()
  '(double-float 0d0 1d0))

(defstruct (color (:constructor %make-color))
  (r 0d0 :type unit-double)
  (g 0d0 :type unit-double)
  (b 0d0 :type unit-double)
  (a 1d0 :type unit-double))

(declaim (inline clamp-df))
(defun clamp-df (x &optional (max-val 1d0))
  (declare (type real x max-val))
  (clamp (coerce (/ x max-val) 'double-float) 0d0 1d0))

(defun rgba (r g b &optional (a 1d0))
  (let ((s (if (and (integerp r) (integerp g) (integerp b)) 255d0 1d0)))
    (%make-color :r (clamp-df r s)
                 :g (clamp-df g s)
                 :b (clamp-df b s)
                 :a (clamp-df a 1d0))))

(defun rgb (r g b)
  (rgba r g b 1d0))

(defun hsl (h s l &optional (a 1d0))
  (let* ((h-deg (mod (coerce h 'double-float) 360d0))
         (s-val (clamp-df s (if (> s 1) 100d0 1d0)))
         (l-val (clamp-df l (if (> l 1) 100d0 1d0)))
         (c (* (- 1d0 (abs (- (* 2d0 l-val) 1d0))) s-val))
         (x (* c (- 1d0 (abs (- (mod (/ h-deg 60d0) 2d0) 1d0)))))
         (m (- l-val (/ c 2d0))))
    (multiple-value-bind (r-prime g-prime b-prime)
        (case (floor h-deg 60)
          (0 (values c x 0d0))
          (1 (values x c 0d0))
          (2 (values 0d0 c x))
          (3 (values 0d0 x c))
          (4 (values x 0d0 c))
          (t (values c 0d0 x)))
      (%make-color :r (+ r-prime m)
                   :g (+ g-prime m)
                   :b (+ b-prime m)
                   :a (clamp-df a 1d0)))))

(defun hsla (h s l a)
  (hsl h s l a))

(defun rgb->hsl (c)
  (let* ((r (color-r c))
         (g (color-g c))
         (b (color-b c))
         (max (max r g b))
         (min (min r g b))
         (delta (- max min))
         (l (/ (+ max min) 2d0)))
    (if (zerop delta)
        (values 0d0 0d0 l)
        (let ((s (/ delta (- 1d0 (abs (- (* 2d0 l) 1d0))))))
          (values (mod (* 60d0 (cond ((= max r) (/ (- g b) delta))
                                     ((= max g) (+ 2d0 (/ (- b r) delta)))
                                     (t        (+ 4d0 (/ (- r g) delta)))))
                       360d0)
                  s
                  l)))))

(defun color->css (c)
  (let ((r (round (* 255 (color-r c))))
        (g (round (* 255 (color-g c))))
        (b (round (* 255 (color-b c))))
        (a (color-a c)))
    (if (< a 1d0)
        (format nil "rgba(~d, ~d, ~d, ~,4f)" r g b a)
        (format nil "rgb(~d, ~d, ~d)" r g b))))

(defun color->hex (c &key with-a)
  (let ((r (round (* 255 (color-r c))))
        (g (round (* 255 (color-g c))))
        (b (round (* 255 (color-b c))))
        (a (round (* 255 (color-a c)))))
    (if (or with-a (< (color-a c) 1d0))
        (format nil "#~2,'0X~2,'0X~2,'0X~2,'0X" r g b a)
        (format nil "#~2,'0X~2,'0X~2,'0X" r g b))))

(defun hex->color (string)
  (let* ((s (string-trim "#" string))
         (len (length s))
         (mv (if (<= len 4) 15d0 255d0)))
    (unless (member len '(3 4 6 8))
      (error "Invalid hex color format: ~s" string))
    (labels ((parse-hex (start end max-val)
               (/ (parse-integer s :start start :end end :radix 16) max-val)))
      (if (<= len 4)
          (%make-color :r (parse-hex 0 1 mv)
                       :g (parse-hex 1 2 mv)
                       :b (parse-hex 2 3 mv)
                       :a (if (= len 4) (parse-hex 3 4 mv) 1d0))
          (%make-color :r (parse-hex 0 2 mv)
                       :g (parse-hex 2 4 mv)
                       :b (parse-hex 4 6 mv)
                       :a (if (= len 8) (parse-hex 6 8 mv) 1d0))))))
